# Generated by Django 3.1.5 on 2021-01-14 12:04

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210114_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageinline',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='home.homepage'),
        ),
    ]
