# Generated by Django 3.1.5 on 2021-01-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactsettings_portfoliopage_socialmediasettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='color_after',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='color_begin',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='transition',
        ),
    ]
