# Generated by Django 3.1.5 on 2021-01-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepageskillshistort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageskillshistort',
            name='slug',
        ),
    ]
