# Generated by Django 3.1.5 on 2021-01-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210112_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliopage',
            old_name='content',
            new_name='body',
        ),
    ]
