# Generated by Django 3.1.5 on 2021-01-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='keywords',
            field=models.TextField(blank=True, help_text='keywords', null=True, verbose_name='keywords'),
        ),
    ]
