# Generated by Django 3.1.5 on 2021-01-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210112_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopage',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='section_des',
            field=models.TextField(blank=True, null=True),
        ),
    ]
