# Generated by Django 3.1.5 on 2021-01-19 06:01

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210119_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='contact_desc',
            new_name='contact_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill_title',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
